services:
  sync:
    env_file: ./sync-plug/.env
    build: ./sync-plug
    container_name: sync
    command: ./bin/run.sh
    volumes:
      - ./sync-plug:/app
    networks:
      - frontend
      - backend

  async:
    env_file: ./async-api/.env
    build: ./async-api
    container_name: async
    command: ./bin/run.sh
    volumes:
      - ./async-api:/app
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - rabbitmq

  configure:
    env_file: ./configure/.env
    build: ./configure
    container_name: configure
    command: ./bin/run.sh
    volumes:
      - ./configure:/app
    networks:
      - backend
    depends_on:
      - rabbitmq

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "15672:15672"
      volumes:
        - ./rabbitmq_data:/var/lib/rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      networks:
        - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx:ro
    networks:
      - frontend
    depends_on:
      - sync
      - async

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge