[project]
name = "ConfigurationConsumer"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic-settings>=2.11.0",
    "faststream[cli] (>=0.6.1,<0.7.0)",
    "faststream[rabbit] (>=0.6.1,<0.7.0)",
    "redis (>=6.4.0,<7.0.0)",
]

[tool.poetry]
package-mode = false