[project]
name = "SyncPlug"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "uvicorn>=0.37.0",
    "aiohttp (>=3.13.0,<4.0.0)",
]

[tool.poetry]
package-mode = false