[project]
name = "ConfigurationService"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "pydantic-settings>=2.11.0",
    "uvicorn>=0.37.0",
    "faststream (>=0.6.1,<0.7.0)",
]

[tool.poetry]
package-mode = false